# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            'blarg'
tagline:          'oeueo'
description:      'An ongoing experiment with static hosting and dynamic thinking.'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Seren Thompson'
  url:            https://twitter.com/serent

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
